# Generated by Django 3.1.1 on 2021-07-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
