SUBSCRIPTION_TYPE_FREE = 1
SUBSCRIPTION_TYPE_TRIAL = 2
SUBSCRIPTION_TYPE_MONTHLY = 3
SUBSCRIPTION_TYPE_ANNUALLY = 4

SUBSCRIPTION_TYPES = (
    (SUBSCRIPTION_TYPE_FREE, 'FREE'),
    (SUBSCRIPTION_TYPE_TRIAL, 'TRIAL'),
    (SUBSCRIPTION_TYPE_MONTHLY, 'MONTHLY'),
    (SUBSCRIPTION_TYPE_ANNUALLY, 'ANNUALLY'),
)

CONTRACT_TYPE_DIRECT = 1
CONTRACT_TYPE_INDIRECT = 2
CONTRACT_TYPE_BOTH = 3

CONTRACT_TYPES = (
    (CONTRACT_TYPE_DIRECT, 'DIRECT'),
    (CONTRACT_TYPE_INDIRECT, 'INDIRECT'),
    (CONTRACT_TYPE_BOTH, 'BOTH'),
)

ELIGIBILITY_GPO_DRIVEN = 1
ELIGIBILITY_SUPPLIER_DRIVEN = 2
ELIGIBILITY_SUPPLIER_LOC = 3
ELIGIBILITY_INDIVIDUAL = 4
ELIGIBILITY_BLANKET = 5

ELIGIBILITIES = (
    (ELIGIBILITY_GPO_DRIVEN, 'GPO DRIVEN (BASE)'),
    (ELIGIBILITY_SUPPLIER_DRIVEN, 'SUPPLIER DRIVEN'),
    (ELIGIBILITY_SUPPLIER_LOC, 'SUPPLIER LOC'),
    (ELIGIBILITY_INDIVIDUAL, 'INDIVIDUAL'),
    (ELIGIBILITY_BLANKET, 'BLANKET'),
)

STATUS_ACTIVE = 1
STATUS_INACTIVE = 2
STATUS_PENDING = 3
STATUS_PROPOSED = 4

STATUSES = (
    (STATUS_ACTIVE, 'Active'),
    (STATUS_INACTIVE, 'Inactive'),
    (STATUS_PENDING, 'Pending'),
    (STATUS_PROPOSED, 'Proposed'),
)

LINE_STATUS_PENDING = 1
LINE_STATUS_APPROVED = 2
LINE_STATUS_DISPUTED = 3

LINE_STATUSES = (
    (LINE_STATUS_PENDING, 'PENDING'),
    (LINE_STATUS_APPROVED, 'APPROVED'),
    (LINE_STATUS_DISPUTED, 'DISPUTED'),
)

EXCEPTION_ACTION_TAKEN_AUTOCORRECT = 'A'
EXCEPTION_ACTION_TAKEN_OVERRIDE = 'O'
EXCEPTION_ACTION_TAKEN_DISPUTED = 'D'
# EA-1520 - If Chargeback passes all validation and is approved, contract/wac price issued fields are not getting filled in
EXCEPTION_ACTION_TAKEN_NONE = 'N'

EXCEPTIONS_ACTIONS_TAKEN = (
    (EXCEPTION_ACTION_TAKEN_AUTOCORRECT, 'Autocorrect'),
    (EXCEPTION_ACTION_TAKEN_OVERRIDE, 'Override'),
    (EXCEPTION_ACTION_TAKEN_DISPUTED, 'Disputed'),
    (EXCEPTION_ACTION_TAKEN_NONE, 'None'),
)

DISPUTE_TYPE_D = 'D'
DISPUTE_TYPE_A = 'A'
DISPUTE_TYPE_I = 'I'

DISPUTE_TYPES = (
    (DISPUTE_TYPE_D, 'D'),
    (DISPUTE_TYPE_A, 'A'),
    (DISPUTE_TYPE_I, 'I'),
)

APPROVED_REASON_NO_ERRORS_ID = '3a3a601e-247f-4474-ae92-b23373f9dc86'
APPROVED_REASON_CORRECTED_CONTRACT_NO_ID = '93a7c127-4a93-41c3-9f68-950e5458f65d'
APPROVED_REASON_CUSTOM_WAC_PRICE_ID = '298b93ba-d553-4ab1-bd0b-f364b1002511'
APPROVED_REASON_CORRECTED_CONTRACT_PRICE_ID = '81b1a117-fc39-4bbb-8745-c2fa66d13751'
APPROVED_REASON_PRICE_OVERRIDE_ID = '037b6163-29f1-4afa-ac75-d6d5b4217fe9'

APPROVED_REASONS = (
    (APPROVED_REASON_NO_ERRORS_ID, 'NO ERRORS'),
    (APPROVED_REASON_CORRECTED_CONTRACT_NO_ID, 'CORRECTED CONTRACT NO'),
    (APPROVED_REASON_CUSTOM_WAC_PRICE_ID, 'CUSTOM WAC PRICE'),
    (APPROVED_REASON_CORRECTED_CONTRACT_PRICE_ID, 'CORRECTED CONTRACT PRICE'),
    (APPROVED_REASON_PRICE_OVERRIDE_ID, 'PRICE OVERRIDE')
)

STAGE_TYPE_IN_PROCESS = 0
STAGE_TYPE_IMPORTED = 1
STAGE_TYPE_VALIDATED = 2
STAGE_TYPE_POSTED = 3
STAGE_TYPE_PROCESSED = 4
STAGE_TYPE_ARCHIVED = 5

STAGES_TYPES = (
    (STAGE_TYPE_IN_PROCESS, 'IN PROCESS'),
    (STAGE_TYPE_IMPORTED, 'IMPORTED'),
    (STAGE_TYPE_VALIDATED, 'VALIDATED'),
    (STAGE_TYPE_POSTED, 'POSTED'),
    (STAGE_TYPE_PROCESSED, 'PROCESSED'),
    (STAGE_TYPE_ARCHIVED, 'ARCHIVED'),
)

SUBSTAGE_TYPE_NO_ERRORS = 0
SUBSTAGE_TYPE_ERRORS = 1
SUBSTAGE_TYPE_DUPLICATES = 2
SUBSTAGE_TYPE_RESUBMISSIONS = 3
SUBSTAGE_TYPE_INVALID = 4
SUBSTAGE_TYPE_WAITING_FOR_RESPONSE = 5

SUBSTAGES_TYPES = (
    (SUBSTAGE_TYPE_NO_ERRORS, 'NO ERRORS'),
    (SUBSTAGE_TYPE_ERRORS, 'ERRORS'),
    (SUBSTAGE_TYPE_DUPLICATES, 'DUPLICATES'),
    (SUBSTAGE_TYPE_RESUBMISSIONS, 'RESUBMISSIONS'),
    (SUBSTAGE_TYPE_INVALID, 'INVALID'),
    (SUBSTAGE_TYPE_WAITING_FOR_RESPONSE, 'WAITING FOR RESPONSE'),
)

PROCESSING_OPTION_ORIGINAL_ID = 1
PROCESSING_OPTION_UWSGI_ID = 2
PROCESSING_OPTION_CELERY_ID = 3

PROCESSING_OPTIONS = (
    (PROCESSING_OPTION_ORIGINAL_ID, 'Original'),
    (PROCESSING_OPTION_UWSGI_ID, 'uWSGI'),
    (PROCESSING_OPTION_CELERY_ID, 'Celery'),
)

# Audit Trail Actions
AUDIT_TRAIL_ACTION_CREATED = 'created'
AUDIT_TRAIL_ACTION_ADDED = 'added'
AUDIT_TRAIL_ACTION_EDITED = 'edited'
AUDIT_TRAIL_ACTION_DELETED = 'deleted'

# Audit Actions for Chargeback
AUDIT_TRAIL_CHARGEBACK_ACTION_844_IMPORT = '844 Import'
AUDIT_TRAIL_CHARGEBACK_ACTION_ARCHIVE = 'Archive'
AUDIT_TRAIL_CHARGEBACK_ACTION_GENERATE_849 = 'Generate 849'
AUDIT_TRAIL_CHARGEBACK_ACTION_POST_TO_ACCOUNTING = 'Post To Accounting'
AUDIT_TRAIL_CHARGEBACK_ACTION_PURGE = 'Purge'
AUDIT_TRAIL_CHARGEBACK_ACTION_IMPORT_FROM_QUICKBOOKS = 'Import from Quickbooks'
AUDIT_TRAIL_CHARGEBACK_ACTION_CREATE_MANUAL_CB = 'Create Manual CB'
AUDIT_TRAIL_CHARGEBACK_ACTION_UPDATE_MANUAL_CB = 'Update Manual CB'

AUDIT_TRAIL_CHARGEBACK_ACTION_ALTER_CONTRACT_NUMBER = 'Alter ContractNo.'
AUDIT_TRAIL_CHARGEBACK_ACTION_DISPUTE = 'Dispute'
AUDIT_TRAIL_CHARGEBACK_ACTION_AUTOCORRECT_PRICE = 'Autocorrect Price'
AUDIT_TRAIL_CHARGEBACK_ACTION_OVERRIDE = 'Override'
AUDIT_TRAIL_CHARGEBACK_ACTION_ALLOW_MEMBER = 'Allow Member'
AUDIT_TRAIL_CHARGEBACK_ACTION_RERUN_VALIDATION = 'Rerun Validations'
AUDIT_TRAIL_CHARGEBACK_ACTION_REVALIDATE = 'Revalidate'

# Rating values
FEEDBACK_RATING_POOR = 1
FEEDBACK_RATING_FAIR = 2
FEEDBACK_RATING_GOOD = 3
FEEDBACK_RATING_EXCELLENT = 4
FEEDBACK_RATING_WOW = 5

RATINGS = (
    (FEEDBACK_RATING_POOR, 'POOR'),
    (FEEDBACK_RATING_FAIR, 'FAIR'),
    (FEEDBACK_RATING_GOOD, 'GOOD'),
    (FEEDBACK_RATING_EXCELLENT, 'EXCELLENT'),
    (FEEDBACK_RATING_WOW, 'WOW'),
)

CB_ACTION_LOG_COMPLETED = 1
CB_ACTION_LOG_INCOMPLETE = 2

CB_ACTION_LOGS = (
    (CB_ACTION_LOG_COMPLETED, 'COMPLETED'),
    (CB_ACTION_LOG_INCOMPLETE, 'INCOMPLETE'),
)

CUSTOMER_TYPE_DISTRIBUTOR = 1
CUSTOMER_TYPE_GPO = 2
CUSTOMER_TYPE_BUYING_GROUP = 3
CUSTOMER_TYPE_PARENT = 4

CUSTOMER_TYPES = (
    (CUSTOMER_TYPE_DISTRIBUTOR, 'Distributor'),
    (CUSTOMER_TYPE_GPO, 'GPO'),
    (CUSTOMER_TYPE_BUYING_GROUP, 'Buying Group'),
    (CUSTOMER_TYPE_PARENT, 'Parent'),
)

GLOBAL_CUSTOMER_ABC_ID = '6203506f-d7e8-4295-b912-9850ea6b4b44'
GLOBAL_CUSTOMER_CAR_ID = '5e817992-3e2f-4c89-9dc9-570c25ed5b81'
GLOBAL_CUSTOMER_MCK_ID = '41f6030e-9cfa-4957-9b6e-47092767d974'

GLOBAL_CUSTOMERS_BIG3_IDS_LIST = [GLOBAL_CUSTOMER_ABC_ID, GLOBAL_CUSTOMER_CAR_ID, GLOBAL_CUSTOMER_MCK_ID]

COLORS_LIST = [
    "red",
    "blue",
    "yellow",
    "green",
    "brown",
    "orange",
    "purple",
    "pink",
    "black",
    "violet",
]

COT_GROUP_GOVERNMENT = 1
COT_GROUP_DISTRIBUTION = 2
COT_GROUP_PROVIDERS = 3
COT_GROUP_RESIDENTIAL = 4
COT_GROUP_NONRETAIL_PHARMACY = 5
COT_GROUP_RETAIL_PHARMACY = 6
COT_GROUP_RETAIL_OTHER_PURCHASERS = 7
COT_GROUP_RETAIL_PAYERS = 8

COT_GROUPS = (
    (COT_GROUP_GOVERNMENT, 'GOVERNMENT'),
    (COT_GROUP_DISTRIBUTION, 'DISTRIBUTION'),
    (COT_GROUP_PROVIDERS, 'PROVIDERS'),
    (COT_GROUP_RESIDENTIAL, 'RESIDENTIAL'),
    (COT_GROUP_NONRETAIL_PHARMACY, 'NON-RETAIL PHARMACY'),
    (COT_GROUP_RETAIL_PHARMACY, 'RETAIL PHARMACY'),
    (COT_GROUP_RETAIL_OTHER_PURCHASERS, 'OTHER PURCHASERS'),
    (COT_GROUP_RETAIL_PAYERS, 'PAYERS'),
)

# Accounting Integration Systems
INTEGRATION_SYSTEM_NONE_ID = '457af242-5119-4ef5-bfad-895a3e23ec29'
INTEGRATION_SYSTEM_MANUAL_ID = 'e2790a81-f1d2-4475-9c44-5315e28156af'
INTEGRATION_SYSTEM_ACUMATICA_ID = '837b7bc6-0dd3-4cea-a21d-7d3431ac2d9b'
INTEGRATION_SYSTEM_QUICKBOOKS_ID = 'e28f8765-d49e-4217-a9bb-108724a978b6'
INTEGRATION_SYSTEM_DYNAMICS365_ID = '3ed12d49-a871-45f7-9abb-bd521778cde0'
INTEGRATION_SYSTEM_NETSUITE_ID = 'd8bd7804-4bf8-45da-b4ee-22f96e609257'

INTEGRATION_SYSTEMS_LIST = (
    (INTEGRATION_SYSTEM_NONE_ID, 'None'),
    (INTEGRATION_SYSTEM_MANUAL_ID, 'Manual'),
    (INTEGRATION_SYSTEM_ACUMATICA_ID, 'Acumatica'),
    (INTEGRATION_SYSTEM_QUICKBOOKS_ID, 'Quickbooks (Local)'),
    (INTEGRATION_SYSTEM_DYNAMICS365_ID, 'Dynamics365'),
    (INTEGRATION_SYSTEM_NETSUITE_ID, 'Netsuite')
)

# MODULES
MODULE_ADMINISTRATION_ID = '32d5bd14-6701-4bd1-8462-cd17d23834b4'
MODULE_CHARGEBACK_ID = '87013fb2-a6d2-4355-8b51-86b6adb8a32d'
MODULE_EDI_ID = '5466c302-6191-471f-8f0c-95cf3ee35072'

# SysAdmin and BetaUser ROLE ID
SYSADMIN_ROLE_ID = "c55a1b32-da16-4e9f-bcee-3a923e42930a"
BETA_USER_ROLE_ID = "ba850281-048c-4c89-9b45-e93a9515b0f5"

# DOCUMENTS_TYPES
DOCUMENT_TYPE_844 = '844'
DOCUMENT_TYPE_849 = '849'
DOCUMENT_TYPE_850 = '850'

DOCUMENTS_TYPES = (
    (DOCUMENT_TYPE_844, '844'),
    (DOCUMENT_TYPE_849, '849'),
    (DOCUMENT_TYPE_850, '850')
)

# EDI MAPPING STATUSES
EDI_MAPPING_STATUS_BUILDING = 1
EDI_MAPPING_STATUS_COMPLETE = 2
EDI_MAPPING_STATUS_DISABLED = 3
EDI_MAPPING_STATUS_ACTIVE = 4

EDI_MAPPING_STATUS_STATUSES = (
    (EDI_MAPPING_STATUS_BUILDING, 'building'),
    (EDI_MAPPING_STATUS_COMPLETE, 'complete'),
    (EDI_MAPPING_STATUS_DISABLED, 'disabled'),
    (EDI_MAPPING_STATUS_ACTIVE, 'active'),
)

# EDI MAPPING OUTPUTS
EDI_MAPPING_OUTPUT_FORMAT_TEXT = 'text'
EDI_MAPPING_OUTPUT_FORMAT_CSV = 'csv'
EDI_MAPPING_OUTPUT_FORMAT_XML = 'xml'

EDI_MAPPING_OUTPUT_FORMATS = (
    (EDI_MAPPING_OUTPUT_FORMAT_TEXT, 'text'),
    (EDI_MAPPING_OUTPUT_FORMAT_CSV, 'csv'),
    (EDI_MAPPING_OUTPUT_FORMAT_XML, 'xml'),
)

# EDI MAPPING TYPES (delimited or fixed width)
EDI_MAPPING_TYPE_DELIMITED = 1
EDI_MAPPING_TYPE_FIXED_WIDTH = 2

EDI_MAPPING_TYPES = (
    (EDI_MAPPING_TYPE_DELIMITED, 'Delimited'),
    (EDI_MAPPING_TYPE_FIXED_WIDTH, 'Fixed Width'),
)

# QUICKBOOKS TRANSACTIONS STATUS
ACCOUNTING_TRANSACTION_STATUS_PENDING = 1
ACCOUNTING_TRANSACTION_STATUS_SENT = 2
ACCOUNTING_TRANSACTION_STATUS_RECEIVED = 3

ACCOUNTING_TRANSACTION_STATUSES = (
    (ACCOUNTING_TRANSACTION_STATUS_PENDING, 'Pending'),
    (ACCOUNTING_TRANSACTION_STATUS_SENT, 'Sent'),
    (ACCOUNTING_TRANSACTION_STATUS_RECEIVED, 'Received'),
)

REPORT_TYPE_CONTRACT = 1
REPORT_TYPE_CHARGEBACK = 2
REPORT_TYPE_MANUAL = 3
REPORT_TYPE_AMP = 4
REPORT_TYPE_CB_DETAIL = 5

REPORT_TYPES = (
    (REPORT_TYPE_CONTRACT, 'Contract'),
    (REPORT_TYPE_CHARGEBACK, 'Chargeback'),
    (REPORT_TYPE_MANUAL, 'Manual'),
    (REPORT_TYPE_AMP, 'AMP'),
    (REPORT_TYPE_CB_DETAIL, 'CB DETAIL'),

)

DATA_RANGE_TD = 'TD'
DATA_RANGE_YD = 'YD'
DATA_RANGE_LM = 'LM'
DATA_RANGE_WTD = 'WTD'
DATA_RANGE_MTD = 'MTD'
DATA_RANGE_YTD = 'YTD'
DATA_RANGE_TW = 'TW'
DATA_RANGE_LW = 'LW'
DATA_RANGE_LY = 'LY'
DATA_RANGE_LQ = 'LQ'
DATA_RANGE_QTD = 'QTD'

DATA_RANGES = (
    (DATA_RANGE_TD, 'Today'),
    (DATA_RANGE_YD, 'Yesterday'),
    (DATA_RANGE_LM, 'Last Month'),
    (DATA_RANGE_WTD, 'Week to Date'),
    (DATA_RANGE_MTD, 'Month to Date'),
    (DATA_RANGE_YTD, 'Year to Date'),
    (DATA_RANGE_TW, 'This Week'),
    (DATA_RANGE_LW, 'Last Week'),
    (DATA_RANGE_LY, 'Last Year'),
    (DATA_RANGE_LQ, 'Last Quarter'),
    (DATA_RANGE_QTD, 'Quarter To Date'),

)

MONTHS = (
    (1, 'January'),
    (2, 'February'),
    (3, 'March'),
    (4, 'April'),
    (5, 'May'),
    (6, 'June'),
    (7, 'July'),
    (8, 'August'),
    (9, 'September'),
    (10, 'October'),
    (11, 'November'),
    (12, 'December'),
)

WEEKDAYS = (
    (0, 'Sunday'),
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (5, 'Friday'),
    (6, 'Saturday'),
)

REPORT_FILTER_TYPE_LT_ID = 'lt'
REPORT_FILTER_TYPE_LTE_ID = 'lte'
REPORT_FILTER_TYPE_GT_ID = 'gt'
REPORT_FILTER_TYPE_GTE_ID = 'gte'
REPORT_FILTER_TYPE_EQUAL_ID = 'exact'
REPORT_FILTER_TYPE_CONTAINS_ID = 'contains'
REPORT_FILTER_TYPE_ICONTAINS_ID = 'icontains'
REPORT_FILTER_TYPE_IN_ID = 'in'
REPORT_FILTER_TYPE_IS_NULL_ID = 'isnull'
REPORT_FILTER_TYPE_EXCLUDE = 'exclude'

REPORT_FILTER_TYPES = (
    (REPORT_FILTER_TYPE_LT_ID, 'Less Than(<)'),
    (REPORT_FILTER_TYPE_LTE_ID, 'Less Than and Equal(<=)'),
    (REPORT_FILTER_TYPE_GT_ID, 'Greater Than(>)'),
    (REPORT_FILTER_TYPE_GTE_ID, 'Greater Than and Equal(>=)'),
    (REPORT_FILTER_TYPE_EQUAL_ID, 'Equal(=)'),
    (REPORT_FILTER_TYPE_CONTAINS_ID, 'Contains(case sensitive)'),
    (REPORT_FILTER_TYPE_ICONTAINS_ID, 'Contains(not case sensitive)'),
    (REPORT_FILTER_TYPE_IN_ID, 'IN'),
    (REPORT_FILTER_TYPE_IS_NULL_ID, 'IsNull'),
    (REPORT_FILTER_TYPE_EXCLUDE, 'Not Equal (!=)'),
)

REPORT_FIELD_SYSTEM = 1
REPORT_FIELD_STATIC = 2
REPORT_FIELD_CALCULATED = 3
REPORT_FIELD_PERCENT = 4
REPORT_FIELD_CASE_STATEMENT = 5

REPORT_FIELD_TYPES = (
    (REPORT_FIELD_SYSTEM, 'System'),
    (REPORT_FIELD_STATIC, 'Static'),
    (REPORT_FIELD_CALCULATED, 'Calculated'),
    (REPORT_FIELD_PERCENT, 'Percent'),
    (REPORT_FIELD_CASE_STATEMENT, 'Case Statement'),
)

MONTHDAYS = (
    (1, '1st of Month'),
    (2, '2nd of Month'),
    (3, '3d of Month'),
    (4, '4th of Month'),
    (5, '5th of Month'),
    (6, '6th of Month'),
    (7, '7th of Month'),
    (8, '8th of Month'),
    (9, '9th of Month'),
    (10, '10th of Month'),
    (11, '11th of Month'),
    (12, '12th of Month'),
    (13, '13th of Month'),
    (14, '14th of Month'),
    (15, '15th of Month'),
    (16, '16th of Month'),
    (17, '17th of Month'),
    (18, '18th of Month'),
    (19, '19th of Month'),
    (20, '20th of Month'),
    (21, '21st of Month'),
    (22, '22nd of Month'),
    (23, '23rd of Month'),
    (24, '24th of Month'),
    (25, '25th of Month'),
    (26, '26th of Month'),
    (27, '27th of Month'),
    (28, '28th of Month'),
    (29, '29th of Month'),
    (30, '30th of Month'),
    (31, '31st of Month')
)

REPORT_SCHEDULE_FREQUENCY_DAILY = 1
REPORT_SCHEDULE_FREQUENCY_WEEKLY = 2
REPORT_SCHEDULE_FREQUENCY_MONTHLY = 3
REPORT_SCHEDULE_FREQUENCY_QUARTARLY = 4

REPORT_SCHEDULE_FREQUENCIES = (
    (REPORT_SCHEDULE_FREQUENCY_DAILY, 'Daily'),
    (REPORT_SCHEDULE_FREQUENCY_WEEKLY, 'Weekly'),
    (REPORT_SCHEDULE_FREQUENCY_MONTHLY, 'Monthly'),
    (REPORT_SCHEDULE_FREQUENCY_QUARTARLY,'Quartarly'),
)
CB_MODULE_PAGE = {
    "Dashboard": "/dashboard",
    "Chargebacks": "/chargebacks",
    "Exceptions": "/chargebacks/exceptions?tab=e",
    "Contracts":"/contracts",
    "Products":"/products",
    "Reports":"/reports",
    "File Manager":"/files"
}

DATE_FORMAT_LIST = {
    "%m/%d/%Y": "mm/dd/YYYY",
    "%m-%d-%Y": "mm-dd-YYYY",
    "%m%d%Y": "mmddYYYY",
    "%d/%m/%Y":"dd/mm/YYYY",
    "%d-%m-%Y":"dd-mm-YYYY",
    "%d%m%Y":"ddmmYYYY",
    "%Y/%m/%d":"YYYY/mm/dd",
    "%Y-%m-%d":"YYYY-mm-dd",
    "%Y%m%d":"YYYYmmdd",
    "%Y%m":"YYYYmm",
    "%m%Y":"mmYYYY",
    "%B":"mm",
    "%Y":"YYYY",
    "%B %d, %Y":"Full Text"
}

CONTRACT_THRESHOLD_VALUE = [30,60,90]